preproc:
  SLIDING_WINDOW_SIZE : 3
training:
  bc:
    BATCH_SIZE : 1024
    DROPOUT_RATE : 0.5
    LEARNING_RATE : 0.0003
    N_EPOCHS : 3500
    OUTPUT_SIZE : 1
    PATIENCE : 1000
    WEIGHT_DECAY : 0
  oc:
    BATCH_SIZE : 1024
    DROPOUT_RATE : 0.5
    LEARNING_RATE : 0.000003
    N_EPOCHS : 8000
    OUTPUT_SIZE : 5
    PATIENCE : 1000
    WEIGHT_DECAY : 0
